modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
description='''
A lightweight, immersive physiology overhaul introducing bone fractures, hypothermia, inventory encumbrance, and sleep fatigue. Features minimalist action-bar feedback, vanilla attribute integration, and zero performance overhead.
'''

[[dependencies.${mod_id}]]
    modId="forge"
    type="required"
    versionRange="${loader_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
